# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61a7cc050645a9350e1e1114111f01155df0a3046abc80d4a8334c8b258680c78869b6ad31c65df72271b67c1358ff81840a10dd1b08e054ab5e5513124a5e68

test:
  secret_key_base: 630d391800d44bfae24149107db67f3b92bbe137682eaacd9518e010416a0bfa62b61386cdb3b8fa47929d728c33c5cb1d5f79a1de77fee8cdfcf97e011fd5c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
